accessKey: AKIA566624WBGFY6FRWH
secret: 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
bucketName: jobfever
region: eu-central-1

spring:
  datasource:
    url: postgresql://localhost:5432/job_fever
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 3000000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
